# Generated by Django 4.1.1 on 2022-11-10 18:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_image_path),
        ),
    ]
