# Generated by Django 4.1.1 on 2023-01-03 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_account_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='users',
            new_name='members',
        ),
    ]
