# Generated by Django 4.1.1 on 2023-01-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_users_chat_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='content',
        ),
    ]
