# Generated by Django 4.1.1 on 2023-03-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_message_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='admins',
            field=models.ManyToManyField(related_name='chat_admins', to='core.account'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(related_name='chat_members', to='core.account'),
        ),
    ]
